const TREESFORSELECT = 6;
const BGSFORSELECT = 10;
const MAXSELECTED = 20;
const GARLANDLINESCOUNT = 8;
const MINAMOUNT = 1;
const MAXAMOUNT = 12;
const RANGEAMOUNT = 1;
const MINYEAR = 1940;
const MAXYEAR = 2020;
const RANGEYAER = 10;
const BALLSTRING = 'шар';
const BELLSTRING = 'колокольчик';
const CONESTRING = 'шишка';
const SNOWFLAKESTRING = 'снежинка';
const TOYSTRING = 'фигурка';
const WHITESTRING = 'белый';
const YELLOWSTRING = 'желтый';
const REDSTRING = 'красный';
const BLUESTRING = 'синий';
const GREENSTRING = 'зелёный';
const BIGSTRING = 'большой';
const NORMALSTRING = 'средний';
const SMALLSTRING = 'малый';

export {
  TREESFORSELECT, MAXSELECTED, BGSFORSELECT, GARLANDLINESCOUNT, MINAMOUNT, MAXAMOUNT, RANGEAMOUNT, MINYEAR, MAXYEAR, RANGEYAER, BALLSTRING, BELLSTRING,
  CONESTRING, SNOWFLAKESTRING, TOYSTRING, WHITESTRING, YELLOWSTRING, REDSTRING, BLUESTRING, GREENSTRING, BIGSTRING, NORMALSTRING, SMALLSTRING,
};
